name: Deploy static content to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2' # match your local Jekyll Ruby version
          bundler-cache: true

      - name: Install Jekyll & dependencies
        run: |
          gem install jekyll
          gem install webrick

      - name: Build site
        run: jekyll build -d _site

      - name: Deploy to GitHub Pages
        uses: actions/configure-pages@v5

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site

      - name: Deploy artifact
        uses: actions/deploy-pages@v4
